- name: Update and Upgrade Raspberry Pi Devices
  hosts: raspberry_pis
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

    - name: Reboot the system
      reboot:
        msg: "Rebooting after update/upgrade"
        connect_timeout: 10
        reboot_timeout: 180
